Update Cake to 2.0
cake-contrib/Cake.AzureDevOps pull request #321
Opened 2022-02-21 22:22 UTC by twenzel

- Update Cake reference to 2.0
- Update packages

2022-02-22 00:14 UTC, twenzel commented
@pascalberger Please have a look.

2022-02-25 12:14 UTC, twenzel commented
@augustoproiete are you also a maintainer of this repository?

2022-02-25 12:20 UTC, pascalberger commented
> @pascalberger Please have a look.

@twenzel Thanks for your contribution 👍 

I already had a look at the PR. Unfortunately I can't merge it like this, since it mixes different things in a single PR (update of build, targeting a new version of Cake, style changes). For a clean history I prefer separate pull requests for separate concerns. 

Can you please split the PR for separate concerns. Also happy to discuss changes in advance in an issue to avoid you doing work which won't be merged afterwards.

2022-02-25 18:50 UTC, augustoproiete commented
@twenzel I'm not, but @pascalberger got you covered

2022-02-25 21:13 UTC, pascalberger requested changes

2022-02-25 21:13 UTC, pascalberger commented on src/Cake.AzureDevOps/Cake.AzureDevOps.csproj
> +    <PackageReleaseNotes>https://github.com/cake-contrib/Cake.AzureDevOps/releases/tag/1.2.0</PackageReleaseNotes>
This is not required in this PR (will become version 2.0 later)

2022-02-25 21:13 UTC, pascalberger commented on src/Cake.AzureDevOps.Tests/Cake.AzureDevOps.Tests.csproj
> +    <PackageReference Include="Microsoft.TeamFoundationServer.Client" Version="16.170.0" />
Please only update required packages. Dependabot will take care of the other later

2022-02-25 21:16 UTC, pascalberger approved these changes
LGTM

2022-02-25 21:24 UTC, merged

2022-02-25 21:26 UTC, pascalberger commented
@twenzel your changes have been merged, thanks for your contribution 👍