Get work item ids from build
cake-contrib/Cake.AzureDevOps pull request #357
Opened 2022-09-24 08:31 UTC by twenzel

Returns a list with work item ids associated with the build.
Fixes #356

2022-09-24 18:29 UTC, pascalberger reviewed
@twenzel Thank you very much for the pull request 👍 

With #361 I'm wondering if we should return a list of `AzureDevOpsWorkItem` instances instead of IDs?

2022-09-24 18:51 UTC, twenzel commented
This feature (Returning WorkItems) will be added afterwards.

2022-09-25 18:53 UTC, pascalberger requested changes
The last commit enhances work item aliases. Can we please keep this PR focus on returning work items of a build and move enhancements to work item aliases to separate PRs

2022-09-25 20:23 UTC, twenzel commented
@pascalberger I removed the last commit

2022-09-26 19:49 UTC, pascalberger commented
> This feature (Returning WorkItems) will be added afterwards.

If there will be a method to return work items, what would be the advantage in also having a `GetWorkItemIds` method?

2022-09-26 19:57 UTC, twenzel commented
> @twenzel If there will be a method to return work items, what would be the advantage in also having a GetWorkItemIds method?

It would be useful when you need to load any work items. The user might have an other source of work item ids than the build.
This is just the start of having work item tracking functionality in Cake.

2022-09-26 20:11 UTC, twenzel commented
@pascalberger I can implement the Build.GetWorkItems method after the PR #364 was merged due to some changes on the WorkItem constructor.

2022-09-26 21:48 UTC, pascalberger commented
> > @twenzel If there will be a method to return work items, what would be the advantage in also having a GetWorkItemIds method?
> 
> It would be useful when you need to load any work items. The user might have an other source of work item ids than the build. This is just the start of having work item tracking functionality in Cake.

Sorry, I still don't get it. When you read work items from somewhere else I don't see how it relates to reading work items from builds.

2022-09-30 18:12 UTC, pascalberger approved these changes
LGTM beside some smaller typos

2022-09-30 18:12 UTC, pascalberger commented on src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs
> +        /// <returns>The work item ids associated with the build.
```suggestion
        /// <returns>The work items associated with the build.
```

2022-09-30 18:22 UTC, merged

2022-09-30 18:59 UTC, pascalberger commented
@twenzel your changes have been merged, thanks for your contribution 👍